name       : haskell-utility-ht
version    : 0.0.15
release    : 1
source     :
    - https://hackage.haskell.org/package/utility-ht-0.0.15/utility-ht-0.0.15.tar.gz : 845c79cdf0925997ec190a761460b50a9577cd290567b9252e31d075cd6f0f91
license    : BSD-3-Clause
component  : programming.haskell
summary    : Various small helper functions for Lists, Maybes, Tuples, Functions
description: |
    Various small helper functions for Lists, Maybes, Tuples, Functions
networking : yes
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
